### ISSUE TITLE
`ggsave` or other means of saving plots from `TidierPlots.jl`

### ISSUE THREAD

**Issue by joshualeond** [TidierOrg/TidierPlots.jl#20]
Hi there, I'm trying out `TidierPlots.jl` and was wondering if there's a recommended way to save a plot? 

Thanks!

**Comment by joshualeond** [comment]
I see we can get there from using `CairoMakie` and `AlgebraOfGraphics` like below but if there's a better route I'm definitely curious to know. Thanks!

```julia
p1 = @ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) + 
    @geom_point() + 
    @geom_smooth(method = "lm") +
    @scale_x_log10(name = "Log10 Scaled Bill Length") + 
    @scale_y_reverse(name = "Reversed Bill Width")

# https://aog.makie.org/stable/generated/penguins/#Small-intermezzo:-saving-the-plot
CairoMakie.save("figure.png", AlgebraOfGraphics.draw(Layers(p1)), px_per_unit = 3)
```

**Comment by kdpsingh** [comment]
We should absolutely add this. If @rdboyes doesn't have bandwidth, will see someine else on our team can help with an initial implementation.

**Comment by rdboyes** [comment]
I don't have the bandwidth this month (unfortunately dissertations don't write themselves) - ideal implementation is probably to add a version of save that takes a GGPlot type. Under the hood it should pretty much work like the code @joshualeond has above.  Tagging this as a good first issue since it's pretty straightforward and self-contained, if nobody does it before the end of the month I'll work on it!

**Comment by rdboyes** [comment]
Or maybe for consistency it should be a macro? `@ggsave`? Both?

**Comment by rdboyes** [comment]
added in https://github.com/TidierOrg/TidierPlots.jl/commit/33238a32b9550d82b13309455d765a40b1782e70
