### ISSUE TITLE
Error while trying to create line plot when X axis is a string

### ISSUE THREAD

**Issue by awojtas-r** [TidierOrg/TidierPlots.jl#22]
I tried to replicate following chart from R
```
df <- data.frame(
  stringsAsFactors = FALSE,
             month = c("January","February","March",
                       "April","May","June","July","August"),
               fin = c(11084,97999,49632,
                       30935,48743,49603,58505,38209)
)
ggplot(df, aes(x = month, y = fin, group = 1)) +geom_line()
```

in Julia
`@ggplot(fnl1, aes(x = mnm, y = financials, group = 1)) +@geom_line()`

but I'm getting following error ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Symbol

Is there any plan to fix it?

**Comment by rdboyes** [comment]
Hi - mostly this is fixed by not including `group = 1`. You need to do a bit of date processing in Julia to get the chart to work right. Either Dates.jl or TidierDates.jl can handle this, e.g.

```
using DataFrames
using TidierPlots
using Dates

d = DataFrame(month = Date.(["2023-01-01",
                    "2023-02-01","2023-03-01",
                    "2023-04-01","2023-05-01",
                    "2023-06-01","2023-07-01","2023-08-01"]),
               fin = [11084,97999,49632,
                       30935,48743,49603,58505,38209])

@ggplot(d, aes(x = month, y = fin)) + @geom_line()
```
![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/b13e6ee5-a602-4dc9-9428-59bd0aa94c54)
