### ISSUE TITLE
Documenter builds are failing

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#52]
Documenter builds are failing with the following error: 

`ERROR: LoadError: MethodError: no method matching wait_for_ready(::Nothing)`

I'm unsure what this means or what is causing it

**Comment by kdpsingh** [comment]
I wonder if the builds are failing because WGLMakie can't find a screen to print to.

The function is referenced in WGLMakie here: https://github.com/MakieOrg/Makie.jl/blob/7d8699742dea80dc417f984473b36ee8535d9a35/WGLMakie/src/display.jl#L208

It comes from the Bonito.jl package, where I think it is defined here: https://github.com/SimonDanisch/Bonito.jl/blob/e2cf265d158e16cd6d97dff9f09488f32777794f/src/session.jl#L21

**Comment by kdpsingh** [comment]
Would using CairoMakie potentially solve this since the output is rendered as images (and doesn't require a WebGL browser)?

**Comment by kdpsingh** [comment]
I'm pretty certain now that this is the issue. See here: https://github.com/orgs/community/discussions/60273

I think the `WGLMakie.activate!()` is what triggers this. I *think* switching to CairoMakie should fix this - am happy to try it if you'd like.

**Comment by rdboyes** [comment]
This was the problem, and it is now fixed! Thanks!
